import { chromium } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
mkdirSync('outputs', {recursive:true});
const browser = await chromium.launch({headless:true, executablePath:process.env.TZCG_CHROMIUM});
const page = await browser.newPage({viewport:{width:1280,height:1000},timezoneId:'Asia/Tokyo'});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.goto(process.env.TZCG_DEMO_URL || 'http://127.0.0.1:5173/');
await page.getByRole('tab',{name:/Grid/}).click();
await page.getByRole('table').waitFor();
await page.screenshot({path:'outputs/grid-desktop.png',fullPage:true});
const desktop = await page.evaluate(() => {
 const marker=document.querySelector('.tzcg-now').getBoundingClientRect();
 const timeline=document.querySelector('.tzcg-timeline').getBoundingClientRect();
 return {markerWithinTimeline:marker.x>=timeline.x&&marker.x<=timeline.right,rows:document.querySelectorAll('.tzcg-grid-body [role=row]').length};
});
if(!desktop.markerWithinTimeline||desktop.rows<4)throw Error('Invalid desktop grid');
await page.context().setOffline(true);
await page.getByRole('combobox').fill('KTM');
await page.getByRole('combobox').press('ArrowDown');
await page.getByRole('combobox').press('Enter');
await page.getByText('KTM',{exact:true}).waitFor();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'outputs/grid-mobile.png',fullPage:true});
const fits=await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);
if(!fits)throw Error('Mobile page overflow');
await page.getByRole('tab',{name:/Lista/}).click();
await page.screenshot({path:'outputs/list-mobile.png',fullPage:true});
if(errors.length)throw Error(errors.join('\n'));
writeFileSync('outputs/VALIDACAO-BROWSER.json',JSON.stringify({desktop,mobileFitsViewport:fits,offlineAirportSearch:true,pageErrors:errors},null,2));
console.log('Desktop, mobile, offline search and marker verified');
await browser.close();
